
tab_spaces=4
reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
use_field_init_shorthand = true
enum_discrim_align_threshold = 20
force_multiline_blocks = true

max_width = 80
